# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# House Price Prediction Using Linear Regression
# Data Source: King County House Sales Dataset
# https://www.kaggle.com/datasets/harlfoxem/housesalesprediction
#
# This dataset contains over 21,000 real house sales.
# This model predicts house prices based on square footage and ZIP code.

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, r2_score

# Data Source: King County House Sales Dataset
# https://www.kaggle.com/datasets/harlfoxem/housesalesprediction

df = pd.read_csv("/content/kc_house_data.csv")


# --------------------------------------------------
# 2. PREPARE THE DATA
# --------------------------------------------------

# Keep the columns needed for this project
df = df[['sqft_living', 'zipcode', 'price']]

# Rename the columns to make them easier to understand
df = df.rename(columns={
    'sqft_living': 'square_footage',
    'zipcode': 'location'
})

# Remove any missing values
df = df.dropna()

# Display the first few records
print("\nFirst 5 houses in the dataset:")
print(df.head())

print("\nNumber of houses in dataset:")
print(len(df))


# --------------------------------------------------
# 3. SET FEATURES AND TARGET
# --------------------------------------------------

# X contains the information used to predict house price
X = df[['square_footage', 'location']]

# y is what we are trying to predict
y = df['price']


# --------------------------------------------------
# 4. CONVERT LOCATION INTO NUMERICAL DATA
# --------------------------------------------------

# OneHotEncoder converts ZIP codes into information
# that the linear regression model can understand.
#
# handle_unknown='ignore' is an improvement that prevents
# errors if the model sees a ZIP code it did not train on.

preprocessor = ColumnTransformer(
    transformers=[
        (
            'location',
            OneHotEncoder(
                handle_unknown='ignore',
                sparse_output=False
            ),
            ['location']
        )
    ],
    remainder='passthrough'
)


# --------------------------------------------------
# 5. CREATE LINEAR REGRESSION MODEL
# --------------------------------------------------

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])


# --------------------------------------------------
# 6. SPLIT DATA INTO TRAINING AND TESTING DATA
# --------------------------------------------------

# 80% of the data will train the model.
# 20% will test how well the model works.

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)


# --------------------------------------------------
# 7. TRAIN THE MODEL
# --------------------------------------------------

model.fit(X_train, y_train)

print("\nModel training complete!")


# --------------------------------------------------
# 8. TEST THE MODEL
# --------------------------------------------------

test_predictions = model.predict(X_test)

# Mean Absolute Error tells us approximately how far
# the model's predictions are from the real prices.

mae = mean_absolute_error(y_test, test_predictions)

# R-squared shows how much of the variation in price
# can be explained by the model.

r2 = r2_score(y_test, test_predictions)

print("\nMODEL PERFORMANCE")
print("--------------------------")
print(f"Mean Absolute Error: ${mae:,.2f}")
print(f"R-squared: {r2:.3f}")


# --------------------------------------------------
# 9. PREDICT THE PRICE OF A NEW HOUSE
# --------------------------------------------------

# Example:
# Predict the price of a 2,000 square foot house
# located in ZIP code 98101.

new_house = pd.DataFrame({
    'square_footage': [2000],
    'location': [98101]
})

predicted_price = model.predict(new_house)

print("\nHOUSE PRICE PREDICTION")
print("--------------------------")
print("Square Footage: 2,000 sq ft")
print("ZIP Code: 98101")
print(f"Predicted Price: ${predicted_price[0]:,.2f}")


# --------------------------------------------------
# 10. DISPLAY MODEL COEFFICIENTS
# --------------------------------------------------

# Get the names of the ZIP-code features
location_features = (
    model.named_steps['preprocessor']
    .named_transformers_['location']
    .get_feature_names_out(['location'])
)

# Because square footage is passed through without encoding,
# add it to the feature names.
feature_names = list(location_features) + ['square_footage']

# Get coefficients from the linear regression model
coefficients = model.named_steps['regressor'].coef_

print("\nMODEL COEFFICIENTS")
print("--------------------------")

for feature, coef in zip(feature_names, coefficients):
    print(f"{feature}: {coef:,.2f}")


# --------------------------------------------------
# 11. SHOW SQUARE FOOTAGE EFFECT
# --------------------------------------------------

# Find the coefficient specifically for square footage
sqft_index = feature_names.index('square_footage')
sqft_coefficient = coefficients[sqft_index]

print("\nSQUARE FOOTAGE EFFECT")
print("--------------------------")
print(
    f"According to the model, each additional square foot "
    f"changes the predicted house price by approximately "
    f"${sqft_coefficient:,.2f}, while keeping location constant."
)

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score


# Data Source: IBM Telco Customer Churn Dataset
# https://github.com/IBM/watsonx-ai-samples/blob/master/cpd4.5/data/customer_churn/WA_FnUseC_TelcoCustomerChurn.csv
# Dataset contains over 7,000 customer records

df = pd.read_csv(
    "https://raw.githubusercontent.com/IBM/watsonx-ai-samples/master/cpd4.5/data/customer_churn/WA_FnUseC_TelcoCustomerChurn.csv"
)


# Convert TotalCharges to numbers
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Remove rows with missing values
df = df.dropna()


# Convert Churn from Yes/No to 1/0
df['Churn'] = df['Churn'].map({
    'Yes': 1,
    'No': 0
})


# Features and target
X = df[
    [
        'tenure',
        'MonthlyCharges',
        'TotalCharges',
        'SeniorCitizen',
        'Contract'
    ]
]

y = df['Churn']


# Numerical and categorical features
numeric_features = [
    'tenure',
    'MonthlyCharges',
    'TotalCharges',
    'SeniorCitizen'
]

categorical_features = [
    'Contract'
]


# Preprocessing:
# Scale numerical features and one-hot encode categorical features
preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            numeric_features
        ),
        (
            'cat',
            OneHotEncoder(
                sparse_output=False,
                handle_unknown='ignore'
            ),
            categorical_features
        )
    ]
)


# Create pipeline with preprocessing and model
model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        (
            'classifier',
            LogisticRegression(
                random_state=42,
                max_iter=1000
            )
        )
    ]
)


# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# Train model
model.fit(X_train, y_train)


# Improvement: test model accuracy
test_predictions = model.predict(X_test)

accuracy = accuracy_score(
    y_test,
    test_predictions
)

print(f"Model Accuracy: {accuracy:.2%}")


# Predict churn probability for a new customer
new_customer = pd.DataFrame({
    'tenure': [12],
    'MonthlyCharges': [70],
    'TotalCharges': [840],
    'SeniorCitizen': [0],
    'Contract': ['Month-to-month']
})


churn_probability = model.predict_proba(
    new_customer
)[0][1]


# Classify based on threshold (0.5)
threshold = 0.5

churn_prediction = (
    1 if churn_probability > threshold else 0
)


print(
    f"\nChurn Probability for new customer: "
    f"{churn_probability:.2%}"
)

print(
    f"Churn Prediction "
    f"(1 = churn, 0 = no churn): "
    f"{churn_prediction}"
)


# Display model coefficients
categorical_names = (
    model.named_steps['preprocessor']
    .named_transformers_['cat']
    .get_feature_names_out(
        categorical_features
    )
    .tolist()
)


feature_names = (
    numeric_features
    + categorical_names
)


coefficients = (
    model.named_steps['classifier']
    .coef_[0]
)


print("\nModel Coefficients:")

for feature, coef in zip(
    feature_names,
    coefficients
):
    print(
        f"{feature}: {coef:.2f}"
    )


# Show number of records used
print(
    f"\nNumber of customer records used: "
    f"{len(df)}"
)

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt


# Data Source: Mall Customers Dataset
# https://github.com/sharmaroshan/Clustering-of-Mall-Customers
# Dataset contains 200 customer records

df = pd.read_csv(
    "https://raw.githubusercontent.com/sharmaroshan/Clustering-of-Mall-Customers/master/Mall_Customers.csv"
)


# Rename columns to make them easier to work with
df = df.rename(columns={
    'Age': 'age',
    'Annual Income (k$)': 'annual_income',
    'Spending Score (1-100)': 'spending_score'
})


# Preprocess data: Select numerical features and scale them
features = [
    'annual_income',
    'spending_score',
    'age'
]

X = df[features]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


# Determine optimal number of clusters using elbow method
inertia = []

K = range(1, 6)

for k in K:
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    kmeans.fit(X_scaled)

    inertia.append(kmeans.inertia_)


# Plot elbow curve
plt.figure(figsize=(8, 5))

plt.plot(K, inertia, 'bo-')

plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia')
plt.title('Elbow Method for Optimal K')

plt.savefig('elbow_plot.png')

plt.show()


# Improvement:
# Use silhouette scores to help choose the best number of clusters

silhouette_scores = []

K_test = range(2, 6)

for k in K_test:
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    cluster_labels = kmeans.fit_predict(X_scaled)

    score = silhouette_score(
        X_scaled,
        cluster_labels
    )

    silhouette_scores.append(score)


# Choose the K with the highest silhouette score
optimal_k = list(K_test)[
    np.argmax(silhouette_scores)
]

print(
    f"Optimal number of clusters: {optimal_k}"
)


# Apply K-Means with optimal K
kmeans = KMeans(
    n_clusters=optimal_k,
    random_state=42,
    n_init=10
)

df['cluster'] = kmeans.fit_predict(
    X_scaled
)


# Analyze clusters
cluster_summary = (
    df.groupby('cluster')[features]
    .mean()
    .round(2)
)

print("\nCluster Characteristics:")

print(cluster_summary)


# Example of targeted strategies
for cluster in range(optimal_k):

    print(
        f"\nCluster {cluster} Strategy:"
    )

    if (
        cluster_summary.loc[
            cluster,
            'spending_score'
        ] > 60
    ):

        print(
            "High-spending customers: "
            "Offer exclusive promotions or loyalty rewards."
        )

    elif (
        cluster_summary.loc[
            cluster,
            'annual_income'
        ] > 70
    ):

        print(
            "Higher-income customers: "
            "Promote premium products or special offers."
        )

    else:

        print(
            "Lower-engagement customers: "
            "Send personalized re-engagement campaigns."
        )


# Save cluster assignments to CSV
df.to_csv(
    'customer_segments.csv',
    index=False
)


# Show number of customer records used
print(
    f"\nNumber of customer records used: {len(df)}"
)

print(
    "\nFiles created:"
)

print(
    "customer_segments.csv"
)

print(
    "elbow_plot.png"
)